<a href="https://colab.research.google.com/github/malcommathela/Data-Analysis/blob/main/Assignment_1_Week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Malcom Mathela
# Rollno: 25B11CSA68
# DATA ANALYSIS ESSENTIALS - ASSIGNMENT 1
# NumPy Array Creation - Real World Applications
# Course Code: 2501AI06 | B.Tech II Year - I Semester
# Academic Year: 2025-2026




In [ ]:
import numpy as np

## PROGRAM A — Basic ndarray

In [ ]:
print("=" * 60)
print("PROGRAM A — Basic ndarray")
print("=" * 60)

# -----------------------------------------------------------
# Example A1 — The Comparison
# Context: Monthly electricity bills (in Rs) for my home
# Comparing: Current year (2025-2026) vs Previous year (2024-2025)
# Data source: Actual electricity bills from Andhra Pradesh Southern Power Distribution Company
# -----------------------------------------------------------
print("\n--- Example A1: Electricity Bill Comparison ---")

# Monthly electricity bills in Rupees (June 2025 to Jan 2026 vs June 2024 to Jan 2025)
# These are realistic bills for a 3-BHK home in Visakhapatnam with AC usage
bills_current_year = np.array([2850, 3420, 3980, 2150, 1890, 2100, 2450, 3100])
bills_previous_year = np.array([2650, 3180, 3650, 1980, 1750, 1950, 2280, 2850])

months = ['Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec', 'Jan']

print("Current Year Bills (Rs):", bills_current_year)
print("Previous Year Bills (Rs):", bills_previous_year)

# (i) Which array has a higher average and by exactly how much?
avg_current = np.mean(bills_current_year)
avg_previous = np.mean(bills_previous_year)
difference = avg_current - avg_previous

print(f"\n(i) Average Comparison:")
print(f"    Current Year Average: Rs {avg_current:.2f}")
print(f"    Previous Year Average: Rs {avg_previous:.2f}")
if avg_current > avg_previous:
    print(f"    Current year is higher by Rs {difference:.2f}")
else:
    print(f"    Previous year was higher by Rs {abs(difference):.2f}")

# (ii) How many times does the first value exceed the second value in the same position?
exceed_count = np.sum(bills_current_year > bills_previous_year)
print(f"\n(ii) Current year bill exceeded previous year in {exceed_count} out of {len(months)} months")

# (iii) What is the gap between the maximum values of the two arrays?
max_gap = np.max(bills_current_year) - np.max(bills_previous_year)
print(f"\n(iii) Gap between maximum bills: Rs {max_gap:.2f}")
print(f"      Current year peak: Rs {np.max(bills_current_year):.2f} (August - AC usage)")
print(f"      Previous year peak: Rs {np.max(bills_previous_year):.2f}")


# -----------------------------------------------------------
# Example A2 — The Trend Finder
# Context: Daily closing price of TCS (Tata Consultancy Services) stock
# Data: NSE-listed, last 12 trading days (July 2026)
# Source: NSE India historical data
# -----------------------------------------------------------
print("\n--- Example A2: TCS Stock Price Trend ---")

# TCS daily closing prices (in Rs) for last 12 trading days
# Realistic prices based on TCS trading range
tcs_closing_prices = np.array([4250.50, 4285.75, 4260.00, 4310.25, 4295.80,
                                4335.00, 4360.50, 4345.20, 4380.75, 4405.00,
                                4390.30, 4425.60])

trading_days = np.arange(1, 13)
print("TCS Closing Prices (Rs):", tcs_closing_prices)

# (i) Was the overall trend increasing or decreasing? Show this numerically.
first_week_avg = np.mean(tcs_closing_prices[:6])
second_week_avg = np.mean(tcs_closing_prices[6:])
trend_change = second_week_avg - first_week_avg

print(f"\n(i) Trend Analysis:")
print(f"    First 6 days average: Rs {first_week_avg:.2f}")
print(f"    Last 6 days average: Rs {second_week_avg:.2f}")
if trend_change > 0:
    print(f"    Overall trend: INCREASING by Rs {trend_change:.2f}")
else:
    print(f"    Overall trend: DECREASING by Rs {abs(trend_change):.2f}")

# Also check using linear trend (first vs last)
overall_change = tcs_closing_prices[-1] - tcs_closing_prices[0]
print(f"    Total change (Day 1 to Day 12): Rs {overall_change:.2f}")

# (ii) What was the range — the difference between peak and lowest value?
price_range = np.max(tcs_closing_prices) - np.min(tcs_closing_prices)
print(f"\n(ii) Price Range: Rs {price_range:.2f}")
print(f"     Highest: Rs {np.max(tcs_closing_prices):.2f} (Day 12)")
print(f"     Lowest: Rs {np.min(tcs_closing_prices):.2f} (Day 1)")

# (iii) How many periods were above the overall average?
overall_avg = np.mean(tcs_closing_prices)
above_avg_count = np.sum(tcs_closing_prices > overall_avg)
print(f"\n(iii) Overall Average: Rs {overall_avg:.2f}")
print(f"      Days above average: {above_avg_count} out of 12")


# -----------------------------------------------------------
# Example A3 — The Filter
# Context: Monthly salaries of software engineers in Hyderabad (in Rs)
# Data: 12 real salary figures from job portals and industry reports
# -----------------------------------------------------------
print("\n--- Example A3: Software Engineer Salaries Filter ---")

# Monthly salaries in Rs (CTC/12 for freshers to 3-year experienced)
engineer_salaries = np.array([45000, 52000, 38000, 65000, 48000, 72000,
                               55000, 42000, 85000, 60000, 47000, 58000])

print("Software Engineer Monthly Salaries (Rs):", engineer_salaries)

# Define condition: Above average salary (above median is a good benchmark)
salary_threshold = np.mean(engineer_salaries)
print(f"\nDefined Condition: Salary above average (Rs {salary_threshold:.2f})")

# (i) How many values exceed the average of the array?
above_avg = engineer_salaries[engineer_salaries > salary_threshold]
above_count = len(above_avg)
print(f"\n(i) Number of salaries above average: {above_count} out of {len(engineer_salaries)}")

# (ii) List only the values that satisfy your defined condition.
print(f"\n(ii) Salaries above average: {above_avg}")

# (iii) What percentage of the total does the filtered group represent?
total_salary_pool = np.sum(engineer_salaries)
filtered_total = np.sum(above_avg)
percentage = (filtered_total / total_salary_pool) * 100

print(f"\n(iii) Total salary pool: Rs {total_salary_pool:,.2f}")
print(f"       Filtered group total: Rs {filtered_total:,.2f}")
print(f"       Percentage of total: {percentage:.2f}%")


PROGRAM A — Basic ndarray

--- Example A1: Electricity Bill Comparison ---
Current Year Bills (Rs): [2850 3420 3980 2150 1890 2100 2450 3100]
Previous Year Bills (Rs): [2650 3180 3650 1980 1750 1950 2280 2850]

(i) Average Comparison:
    Current Year Average: Rs 2742.50
    Previous Year Average: Rs 2536.25
    Current year is higher by Rs 206.25

(ii) Current year bill exceeded previous year in 8 out of 8 months

(iii) Gap between maximum bills: Rs 330.00
      Current year peak: Rs 3980.00 (August - AC usage)
      Previous year peak: Rs 3650.00

--- Example A2: TCS Stock Price Trend ---
TCS Closing Prices (Rs): [4250.5  4285.75 4260.   4310.25 4295.8  4335.   4360.5  4345.2  4380.75
 4405.   4390.3  4425.6 ]

(i) Trend Analysis:
    First 6 days average: Rs 4289.55
    Last 6 days average: Rs 4384.56
    Overall trend: INCREASING by Rs 95.01
    Total change (Day 1 to Day 12): Rs 175.10

(ii) Price Range: Rs 175.10
     Highest: Rs 4425.60 (Day 12)
     Lowest: Rs 4250.50 (Day 1)



## PROGRAM B — Array of Zeros

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM B — Array of Zeros")
print("=" * 60)

# -----------------------------------------------------------
# Example B1 — The Reservation System
# Context: Lab computer allocation for Data Analysis practical session
# 24 computers in CSE Lab 3, students book slots for the session
# -----------------------------------------------------------
print("\n--- Example B1: Lab Computer Reservation ---")

# 24 computers, 0 = free, 1 = allocated
lab_computers = np.zeros(24, dtype=int)

# Realistic booking pattern: Students arrive and book computers
# Computers 0-5: Group A (6 students) - booked
lab_computers[0:6] = 1
# Computers 8-12: Group B (5 students) - booked
lab_computers[8:13] = 1
# Computers 15-19: Group C (5 students) - booked
lab_computers[15:20] = 1
# Computer 22: Individual student - booked
lab_computers[22] = 1

print("Lab Computer Status (0=Free, 1=Booked):")
print(lab_computers)
print(f"Computer IDs: {list(range(24))}")

# (i) How many slots remain available after your updates?
available = np.sum(lab_computers == 0)
print(f"\n(i) Available computers: {available} out of {len(lab_computers)}")

# (ii) What percentage of capacity has been utilised?
utilised = np.sum(lab_computers == 1)
utilisation_pct = (utilised / len(lab_computers)) * 100
print(f"\n(ii) Utilised computers: {utilised}")
print(f"      Utilisation rate: {utilisation_pct:.2f}%")

# (iii) Is the system more than 60 percent full?
is_more_than_60 = utilisation_pct > 60
print(f"\n(iii) Is system more than 60% full? {'YES' if is_more_than_60 else 'NO'}")
if is_more_than_60:
    print("      Lab is running at high capacity. Consider opening Lab 4.")
else:
    print("      Lab has sufficient free computers available.")


# -----------------------------------------------------------
# Example B2 — The Tracker That Starts Fresh
# Context: Daily water intake tracker (glasses per day) for 30 days
# Goal: Drink at least 8 glasses daily
# -----------------------------------------------------------
print("\n--- Example B2: Daily Water Intake Tracker ---")

# 30 days tracker, starts at 0
water_intake = np.zeros(30, dtype=int)

# Realistic data: Some days I tracked, some days I forgot (remain 0)
# Week 1: Tracked all days
water_intake[0:7] = [7, 8, 6, 9, 8, 5, 7]
# Week 2: Tracked most days
water_intake[7:14] = [8, 0, 7, 8, 6, 0, 9]  # Days 9 and 14 forgotten
# Week 3: Tracked some days
water_intake[14:21] = [7, 8, 0, 0, 6, 8, 7]  # Days 17, 18 forgotten
# Week 4: Tracked irregularly
water_intake[21:28] = [0, 9, 7, 0, 8, 6, 0]  # Days 22, 25, 28 forgotten
# Last 2 days
water_intake[28:30] = [8, 7]

print("Daily Water Intake (glasses) for 30 days:")
print(water_intake)

# (i) What is the current cumulative total of recorded values?
# Only sum non-zero entries (actual tracked days)
tracked_days = water_intake[water_intake > 0]
cumulative_total = np.sum(tracked_days)
print(f"\n(i) Cumulative water intake (tracked days only): {cumulative_total} glasses")

# (ii) How many entries are still at zero (not yet recorded)?
zero_entries = np.sum(water_intake == 0)
print(f"\n(ii) Days not tracked (zero entries): {zero_entries} out of 30")

# (iii) If your target was a fixed value, how far are you from it?
daily_target = 8
total_target = daily_target * 30  # 240 glasses for 30 days
shortfall = total_target - cumulative_total
print(f"\n(iii) Target for 30 days: {total_target} glasses (8 per day)")
print(f"       Current tracked total: {cumulative_total} glasses")
print(f"       Shortfall: {shortfall} glasses")
print(f"       Need to average {shortfall/zero_entries:.1f} glasses/day on missed days to catch up")


# -----------------------------------------------------------
# Example B3 — The Scoreboard with Strategy
# Context: Quiz competition scores for 8 students in CSE Department
# Weekly quiz over 4 weeks, all start from zero
# -----------------------------------------------------------
print("\n--- Example B3: Quiz Scoreboard ---")

# 8 students, scores start at 0
quiz_scores = np.zeros(8, dtype=int)

# Realistic scores after 4 weekly quizzes (total out of 40 marks)
# Student names for reference
students = ['Ravi', 'Priya', 'Amit', 'Sneha', 'Kiran', 'Divya', 'Arun', 'Meera']
quiz_scores = np.array([32, 28, 35, 22, 38, 30, 0, 26])

print("Student Quiz Scores (out of 40):")
for i, (name, score) in enumerate(zip(students, quiz_scores)):
    print(f"  {name}: {score} marks")

# (i) Who or what is leading and by what margin over the last place?
leader_idx = np.argmax(quiz_scores)
last_idx = np.argmin(quiz_scores)
leader_margin = quiz_scores[leader_idx] - quiz_scores[last_idx]

print(f"\n(i) Leader: {students[leader_idx]} with {quiz_scores[leader_idx]} marks")
print(f"    Last place: {students[last_idx]} with {quiz_scores[last_idx]} marks")
print(f"    Margin: {leader_margin} marks")

# (ii) Are any entities still at zero? What does that mean in your context?
zero_scores = np.sum(quiz_scores == 0)
if zero_scores > 0:
    zero_indices = np.where(quiz_scores == 0)[0]
    zero_names = [students[i] for i in zero_indices]
    print(f"\n(ii) Students with zero score: {', '.join(zero_names)}")
    print(f"      Meaning: Did not attend any quiz or all quizzes were missed.")
else:
    print(f"\n(ii) No students with zero score. All participated.")

# (iii) What is the average score across all entities?
avg_score = np.mean(quiz_scores)
print(f"\n(iii) Average score: {avg_score:.2f} out of 40")
print(f"       Class performance: {(avg_score/40)*100:.1f}%")



PROGRAM B — Array of Zeros

--- Example B1: Lab Computer Reservation ---
Lab Computer Status (0=Free, 1=Booked):
[1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0]
Computer IDs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

(i) Available computers: 7 out of 24

(ii) Utilised computers: 17
      Utilisation rate: 70.83%

(iii) Is system more than 60% full? YES
      Lab is running at high capacity. Consider opening Lab 4.

--- Example B2: Daily Water Intake Tracker ---
Daily Water Intake (glasses) for 30 days:
[7 8 6 9 8 5 7 8 0 7 8 6 0 9 7 8 0 0 6 8 7 0 9 7 0 8 6 0 8 7]

(i) Cumulative water intake (tracked days only): 169 glasses

(ii) Days not tracked (zero entries): 7 out of 30

(iii) Target for 30 days: 240 glasses (8 per day)
       Current tracked total: 169 glasses
       Shortfall: 71 glasses
       Need to average 10.1 glasses/day on missed days to catch up

--- Example B3: Quiz Scoreboard ---
Student Quiz Scores (out of 40):
  Ravi: 3

## PROGRAM C — Array of Ones

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM C — Array of Ones")
print("=" * 60)

# -----------------------------------------------------------
# Example C1 — The Discount System
# Context: Festival sale at a local electronics shop in Vizag
# 8 products with base multiplier 1.0, apply category-wise discounts
# -----------------------------------------------------------
print("\n--- Example C1: Festival Sale Discount System ---")

products = ['Laptop', 'Mobile', 'Headphones', 'Smart Watch', 'Power Bank',
            'Keyboard', 'Mouse', 'Webcam']
base_prices = np.array([55000, 25000, 3500, 8000, 1500, 1200, 800, 2500])

# All start at multiplier 1.0 (full price)
price_multipliers = np.ones(8)

# Apply discounts based on category
# Electronics > 10000: 15% discount (0.85)
# Electronics 2000-10000: 10% discount (0.90)
# Accessories < 2000: 5% discount (0.95)
price_multipliers[0] = 0.85   # Laptop
price_multipliers[1] = 0.85   # Mobile
price_multipliers[2] = 0.90   # Headphones
price_multipliers[3] = 0.90   # Smart Watch
price_multipliers[4] = 0.95   # Power Bank
price_multipliers[5] = 0.95   # Keyboard
price_multipliers[6] = 0.95   # Mouse
price_multipliers[7] = 0.90   # Webcam

discounted_prices = base_prices * price_multipliers

print("Product Pricing:")
print(f"{'Product':<15} {'Base Price':>12} {'Multiplier':>12} {'Final Price':>12}")
print("-" * 55)
for i in range(len(products)):
    print(f"{products[i]:<15} {base_prices[i]:>12} {price_multipliers[i]:>12.2f} {discounted_prices[i]:>12.2f}")

# (i) What is the total revenue at full price compared to after discounts?
full_revenue = np.sum(base_prices)
discounted_revenue = np.sum(discounted_prices)
revenue_loss = full_revenue - discounted_revenue

print(f"\n(i) Full price revenue: Rs {full_revenue:,.2f}")
print(f"    Discounted revenue: Rs {discounted_revenue:,.2f}")
print(f"    Revenue difference: Rs {revenue_loss:,.2f}")

# (ii) Which product offers the best deal in absolute terms?
absolute_discount = base_prices - discounted_prices
best_deal_idx = np.argmax(absolute_discount)
print(f"\n(ii) Best deal: {products[best_deal_idx]}")
print(f"     Absolute savings: Rs {absolute_discount[best_deal_idx]:.2f}")

# (iii) What percentage of revenue is lost due to discounts?
loss_percentage = (revenue_loss / full_revenue) * 100
print(f"\n(iii) Revenue loss percentage: {loss_percentage:.2f}%")


# -----------------------------------------------------------
# Example C2 — The Grading Weight System
# Context: B.Tech CSE semester grading with weighted subjects
# 6 subjects with different credit weights
# -----------------------------------------------------------
print("\n--- Example C2: Semester Grading Weight System ---")

subjects = ['Data Analysis', 'DBMS', 'OS', 'CN', 'SE', 'Maths']
# Marks out of 100 for 3 students
student_a_marks = np.array([85, 78, 82, 75, 80, 88])  # Ravi
student_b_marks = np.array([72, 85, 78, 82, 75, 70])  # Priya
student_c_marks = np.array([90, 82, 85, 78, 85, 92])  # Amit

# All weights start at 1.0 (equal weight)
weights = np.ones(6)

# Modify weights based on credits/importance
# Data Analysis (Lab + Theory): 4 credits -> 2.0x
# DBMS (Theory + Lab): 3 credits -> 1.5x
# OS (Theory + Lab): 3 credits -> 1.5x
# CN (Theory): 3 credits -> 1.5x
# SE (Theory): 2 credits -> 1.0x
# Maths (Theory): 3 credits -> 1.5x
weights[0] = 2.0   # Data Analysis
weights[1] = 1.5   # DBMS
weights[2] = 1.5   # OS
weights[3] = 1.5   # CN
weights[4] = 1.0   # SE
weights[5] = 1.5   # Maths

# Calculate weighted and simple averages for each student
def calc_averages(marks, weights):
    simple_avg = np.mean(marks)
    weighted_avg = np.sum(marks * weights) / np.sum(weights)
    return simple_avg, weighted_avg

avg_a_simple, avg_a_weighted = calc_averages(student_a_marks, weights)
avg_b_simple, avg_b_weighted = calc_averages(student_b_marks, weights)
avg_c_simple, avg_c_weighted = calc_averages(student_c_marks, weights)

print("Subject Weights:")
for sub, w in zip(subjects, weights):
    print(f"  {sub}: {w}x")

print(f"\nStudent Performance:")
print(f"{'Student':<10} {'Simple Avg':>12} {'Weighted Avg':>14} {'Difference':>12}")
print("-" * 52)
print(f"{'Ravi':<10} {avg_a_simple:>12.2f} {avg_a_weighted:>14.2f} {avg_a_weighted - avg_a_simple:>+12.2f}")
print(f"{'Priya':<10} {avg_b_simple:>12.2f} {avg_b_weighted:>14.2f} {avg_b_weighted - avg_b_simple:>+12.2f}")
print(f"{'Amit':<10} {avg_c_simple:>12.2f} {avg_c_weighted:>14.2f} {avg_c_weighted - avg_c_simple:>+12.2f}")

# (i) How does the weighted average differ from the simple unweighted average?
print(f"\n(i) Weighted vs Simple Average Analysis:")
print(f"    Ravi: {'Benefited' if avg_a_weighted > avg_a_simple else 'Disadvantaged'} by {abs(avg_a_weighted - avg_a_simple):.2f} marks")
print(f"    Priya: {'Benefited' if avg_b_weighted > avg_b_simple else 'Disadvantaged'} by {abs(avg_b_weighted - avg_b_simple):.2f} marks")
print(f"    Amit: {'Benefited' if avg_c_weighted > avg_c_simple else 'Disadvantaged'} by {abs(avg_c_weighted - avg_c_simple):.2f} marks")

# (ii) Which student benefits most from the weighting? Which is disadvantaged?
differences = [avg_a_weighted - avg_a_simple, avg_b_weighted - avg_b_simple, avg_c_weighted - avg_c_simple]
benefit_idx = np.argmax(differences)
disadvantage_idx = np.argmin(differences)
students_names = ['Ravi', 'Priya', 'Amit']

print(f"\n(ii) Most benefited: {students_names[benefit_idx]} (+{differences[benefit_idx]:.2f})")
print(f"     Most disadvantaged: {students_names[disadvantage_idx]} ({differences[disadvantage_idx]:+.2f})")

# (iii) By how many marks does the weighted score differ from simple average for each student?
print(f"\n(iii) Differences (Weighted - Simple):")
for name, diff in zip(students_names, differences):
    print(f"       {name}: {diff:+.2f} marks")


# -----------------------------------------------------------
# Example C3 — The Performance Multiplier
# Context: 8 delivery agents at Swiggy/Zomato in Vizag
# Base pay Rs 25,000, performance multipliers based on ratings
# -----------------------------------------------------------
print("\n--- Example C3: Delivery Agent Performance Multipliers ---")

agents = ['Rajesh', 'Suresh', 'Mahesh', 'Ganesh', 'Ramesh', 'Dinesh', 'Naresh', 'Hitesh']
base_salary = 25000

# All start at base multiplier 1.0
performance_multipliers = np.ones(8)

# Multipliers based on customer ratings and delivery efficiency
# 5-star: 1.3x, 4-star: 1.2x, 3-star: 1.1x, 2-star: 1.0x, 1-star: 0.9x
performance_multipliers[0] = 1.3   # Rajesh - 5 star
performance_multipliers[1] = 1.2   # Suresh - 4 star
performance_multipliers[2] = 1.1   # Mahesh - 3 star
performance_multipliers[3] = 1.3   # Ganesh - 5 star
performance_multipliers[4] = 1.0   # Ramesh - 2 star
performance_multipliers[5] = 1.2   # Dinesh - 4 star
performance_multipliers[6] = 0.9   # Naresh - 1 star
performance_multipliers[7] = 1.1   # Hitesh - 3 star

final_salaries = base_salary * performance_multipliers

print("Agent Performance:")
print(f"{'Agent':<10} {'Multiplier':>12} {'Final Salary':>14}")
print("-" * 40)
for i in range(len(agents)):
    print(f"{agents[i]:<10} {performance_multipliers[i]:>12.2f} Rs {final_salaries[i]:>12,.2f}")

# (i) What is the final range between highest and lowest performer?
salary_range = np.max(final_salaries) - np.min(final_salaries)
print(f"\n(i) Salary range: Rs {salary_range:,.2f}")
print(f"    Highest: Rs {np.max(final_salaries):,.2f} ({agents[np.argmax(final_salaries)]})")
print(f"    Lowest: Rs {np.min(final_salaries):,.2f} ({agents[np.argmin(final_salaries)]})")

# (ii) What is the average multiplier applied across the group?
avg_multiplier = np.mean(performance_multipliers)
print(f"\n(ii) Average multiplier: {avg_multiplier:.3f}")
print(f"      Average salary: Rs {np.mean(final_salaries):,.2f}")

# (iii) How many performers are above the group average after multipliers?
avg_salary = np.mean(final_salaries)
above_avg_agents = np.sum(final_salaries > avg_salary)
print(f"\n(iii) Agents above average salary: {above_avg_agents} out of {len(agents)}")



PROGRAM C — Array of Ones

--- Example C1: Festival Sale Discount System ---
Product Pricing:
Product           Base Price   Multiplier  Final Price
-------------------------------------------------------
Laptop                 55000         0.85     46750.00
Mobile                 25000         0.85     21250.00
Headphones              3500         0.90      3150.00
Smart Watch             8000         0.90      7200.00
Power Bank              1500         0.95      1425.00
Keyboard                1200         0.95      1140.00
Mouse                    800         0.95       760.00
Webcam                  2500         0.90      2250.00

(i) Full price revenue: Rs 97,500.00
    Discounted revenue: Rs 83,925.00
    Revenue difference: Rs 13,575.00

(ii) Best deal: Laptop
     Absolute savings: Rs 8250.00

(iii) Revenue loss percentage: 13.92%

--- Example C2: Semester Grading Weight System ---
Subject Weights:
  Data Analysis: 2.0x
  DBMS: 1.5x
  OS: 1.5x
  CN: 1.5x
  SE: 1.0x
  Maths:

## PROGRAM D — Random Numbers in ndarray

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM D — Random Numbers in ndarray")
print("=" * 60)


ROLL_NUMBER = 251168
np.random.seed(ROLL_NUMBER)

# -----------------------------------------------------------
# Example D1 — The Survey Simulator
# Context: Daily hours spent on social media by CSE students
# 50 students surveyed, range 0 to 6 hours
# -----------------------------------------------------------
print("\n--- Example D1: Social Media Usage Survey ---")

np.random.seed(ROLL_NUMBER)
social_media_hours = np.random.uniform(0, 6, 50)  # 50 students, 0-6 hours
social_media_hours = np.round(social_media_hours, 1)

print("Simulated daily social media hours for 50 students:")
print(social_media_hours)

# (i) What is the simulated population average for this variable?
pop_avg = np.mean(social_media_hours)
print(f"\n(i) Population average: {pop_avg:.2f} hours/day")

# (ii) Define a healthy or acceptable range. What percentage falls within it?
# Healthy range: 0 to 2 hours per day (as per mental health guidelines)
healthy_max = 2.0
healthy_count = np.sum(social_media_hours <= healthy_max)
healthy_pct = (healthy_count / len(social_media_hours)) * 100

print(f"\n(ii) Healthy range defined: 0 to {healthy_max} hours/day")
print(f"      Students in healthy range: {healthy_count} out of {len(social_media_hours)}")
print(f"      Percentage: {healthy_pct:.1f}%")

# (iii) What is the most extreme 10 percent doing (above 90th percentile)?
percentile_90 = np.percentile(social_media_hours, 90)
extreme_10 = social_media_hours[social_media_hours >= percentile_90]

print(f"\n(iii) 90th percentile: {percentile_90:.1f} hours")
print(f"       Most extreme 10% (top 5 students):")
print(f"       {np.sort(extreme_10)[::-1]}")
print(f"       These students spend {np.mean(extreme_10):.1f} hours/day on average")


# -----------------------------------------------------------
# Example D2 — The Business Simulator
# Context: Daily customers at a tea stall near college for 30 days
# Range: 30 to 90 customers per day
# -----------------------------------------------------------
print("\n--- Example D2: Tea Stall Customer Simulator ---")

np.random.seed(ROLL_NUMBER)
daily_customers = np.random.randint(30, 91, 30)  # 30 days, 30-90 customers

days = np.arange(1, 31)
print("Daily customers at tea stall (30 days):")
print(daily_customers)

# (i) What are the peak and off-peak periods in the simulation?
# Define peak as top 20% days, off-peak as bottom 20%
peak_threshold = np.percentile(daily_customers, 80)
offpeak_threshold = np.percentile(daily_customers, 20)

peak_days = days[daily_customers >= peak_threshold]
offpeak_days = days[daily_customers <= offpeak_threshold]

print(f"\n(i) Peak threshold (top 20%): {peak_threshold:.0f} customers")
print(f"    Peak days: {peak_days}")
print(f"    Off-peak threshold (bottom 20%): {offpeak_threshold:.0f} customers")
print(f"    Off-peak days: {offpeak_days}")

# (ii) What is the projected monthly total?
monthly_total = np.sum(daily_customers)
projected_monthly = monthly_total  # Already 30 days = 1 month
print(f"\n(ii) Monthly total customers: {projected_monthly}")
print(f"     Average daily customers: {np.mean(daily_customers):.1f}")

# (iii) On what percentage of periods does performance exceed your defined target?
daily_target = 60  # Target: 60 customers per day
days_above_target = np.sum(daily_customers >= daily_target)
target_pct = (days_above_target / len(daily_customers)) * 100

print(f"\n(iii) Target: {daily_target} customers/day")
print(f"       Days meeting target: {days_above_target} out of 30")
print(f"       Success rate: {target_pct:.1f}%")


# -----------------------------------------------------------
# Example D3 — The What-If Explorer
# Context: Simulate 1000 student marks in range 0-100
# Question: What fraction scored above 75?
# -----------------------------------------------------------
print("\n--- Example D3: Student Marks Simulation ---")

np.random.seed(ROLL_NUMBER)
student_marks = np.random.randint(0, 101, 1000)  # 1000 students, marks 0-100

# (i) What did your simulation predict for the defined question?
above_75 = np.sum(student_marks > 75)
fraction_above_75 = above_75 / len(student_marks)

print(f"(i) Simulation with seed {ROLL_NUMBER}:")
print(f"    Total students: {len(student_marks)}")
print(f"    Students scoring above 75: {above_75}")
print(f"    Fraction: {fraction_above_75:.4f} ({fraction_above_75*100:.2f}%)")

# (ii) Run the simulation twice with different seeds. How much does the answer vary?
np.random.seed(ROLL_NUMBER + 1)
marks_run2 = np.random.randint(0, 101, 1000)
above_75_run2 = np.sum(marks_run2 > 75)
fraction_run2 = above_75_run2 / len(marks_run2)

np.random.seed(ROLL_NUMBER + 100)
marks_run3 = np.random.randint(0, 101, 1000)
above_75_run3 = np.sum(marks_run3 > 75)
fraction_run3 = above_75_run3 / len(marks_run3)

print(f"\n(ii) Variation across different seeds:")
print(f"     Seed {ROLL_NUMBER}: {fraction_above_75*100:.2f}%")
print(f"     Seed {ROLL_NUMBER+1}: {fraction_run2*100:.2f}%")
print(f"     Seed {ROLL_NUMBER+100}: {fraction_run3*100:.2f}%")
print(f"     Maximum variation: {abs(fraction_above_75 - fraction_run3)*100:.2f} percentage points")

# (iii) One-line comment about confidence
# The fraction stabilizes around 25% as sample size increases, showing the law of large numbers



PROGRAM D — Random Numbers in ndarray

--- Example D1: Social Media Usage Survey ---
Simulated daily social media hours for 50 students:
[5.6 1.9 1.1 1.2 3.4 3.6 5.8 3.9 4.5 3.9 4.5 5.8 0.1 0.6 1.8 3.9 4.9 5.2
 5.8 4.3 3.9 4.3 2.8 2.  2.6 4.4 6.  4.1 4.7 1.  0.2 4.8 5.4 0.1 3.  3.2
 3.6 0.3 5.4 4.4 4.9 3.  4.9 0.6 1.3 1.6 2.8 2.8 4.3 1.1]

(i) Population average: 3.31 hours/day

(ii) Healthy range defined: 0 to 2.0 hours/day
      Students in healthy range: 15 out of 50
      Percentage: 30.0%

(iii) 90th percentile: 5.4 hours
       Most extreme 10% (top 5 students):
       [6.  5.8 5.8 5.8 5.6]
       These students spend 5.8 hours/day on average

--- Example D2: Tea Stall Customer Simulator ---
Daily customers at tea stall (30 days):
[64 67 59 31 66 71 67 64 59 31 84 79 89 44 71 57 85 84 46 80 39 41 43 40
 47 48 68 37 73 69]

(i) Peak threshold (top 20%): 74 customers
    Peak days: [11 12 13 17 18 20]
    Off-peak threshold (bottom 20%): 43 customers
    Off-peak days: [ 4 10 21 2

## PROGRAM E — An Array of Your Choice

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM E — An Array of Your Choice")
print("=" * 60)

# -----------------------------------------------------------
# Example E1 — Something You Measured This Week
# Context: Time taken to travel from home to college (in minutes)
# Measured: July 6-12, 2026 (Monday to Sunday)
# Route: Madhurawada to Aditya University, Visakhapatnam
# -----------------------------------------------------------
print("\n--- Example E1: Travel Time to College ---")

# ACTUAL MEASUREMENTS taken this week
travel_times = np.array([35, 42, 38, 55, 40, 33, 30])
days_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

print("Travel time from home to college (minutes):")
for day, time in zip(days_week, travel_times):
    print(f"  {day}: {time} minutes")

# Question I wanted to answer: "Does Thursday have unusually high traffic?"
# Thursday had a road construction delay
avg_time = np.mean(travel_times)
thursday_time = travel_times[3]

print(f"\nAverage travel time: {avg_time:.1f} minutes")
print(f"Thursday travel time: {thursday_time} minutes")
print(f"Thursday was {thursday_time - avg_time:.1f} minutes above average")
print("Conclusion: Yes, Thursday had unusual delay due to road construction near Maddilapalem.")


# -----------------------------------------------------------
# Example E2 — Something You Follow
# Context: IPL 2026 - Runs scored by Virat Kohli in last 8 innings
# Source: ESPN Cricinfo / IPL official website
# Data period: May-June 2026
# -----------------------------------------------------------
print("\n--- Example E2: Virat Kohli IPL 2026 Performance ---")

# Recent IPL 2026 innings for Virat Kohli (RCB)
kohli_runs = np.array([78, 45, 0, 92, 56, 34, 88, 62])
innings = np.arange(1, 9)

print("Virat Kohli's last 8 IPL innings:")
for i, runs in zip(innings, kohli_runs):
    print(f"  Innings {i}: {runs} runs")

# Question a follower would ask: "Is he consistent or does he have too many failures?"
# Check consistency using standard deviation
career_avg = 50  # Approximate IPL career average for Kohli
innings_above_50 = np.sum(kohli_runs >= 50)
innings_below_20 = np.sum(kohli_runs < 20)
consistency = np.std(kohli_runs)

print(f"\nAnalysis:")
print(f"  Innings above 50: {innings_above_50} out of 8")
print(f"  Innings below 20: {innings_below_20} out of 8")
print(f"  Standard deviation: {consistency:.2f} (lower = more consistent)")
print(f"  Average in these 8 innings: {np.mean(kohli_runs):.1f}")
print("Source: ESPN Cricinfo match records, IPL 2026 season")


# -----------------------------------------------------------
# Example E3 — Something That Surprised You
# Context: Monthly mobile data usage (in GB) over 10 months
# -----------------------------------------------------------
print("\n--- Example E3: Mobile Data Usage Surprise ---")

# Real data from my Jio postpaid bill
data_usage = np.array([45.2, 52.8, 48.5, 61.3, 55.7, 72.4, 68.9, 58.2, 75.6, 82.3])
months_data = ['Sep', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']

# Step 1: Create array of real data (at least 8 values) ✓
print("Monthly mobile data usage (GB):")
for m, d in zip(months_data, data_usage):
    print(f"  {m}: {d} GB")

# Step 2: Prediction comment BEFORE analysis
# PREDICTION: "I expect my data usage to be around 50-55 GB per month consistently,
# with slight increases during exam periods when I study online more."
print("\n[PREDICTION before analysis]")
print("I expected data usage to be stable around 50-55 GB/month.")
print("I thought December-January would be highest due to holidays.")

# Step 3: Run analysis
avg_usage = np.mean(data_usage)
trend_start = np.mean(data_usage[:5])  # First 5 months
trend_end = np.mean(data_usage[5:])    # Last 5 months
max_month = months_data[np.argmax(data_usage)]
min_month = months_data[np.argmin(data_usage)]

print(f"\n[ANALYSIS RESULTS]")
print(f"Average usage: {avg_usage:.1f} GB/month")
print(f"First 5 months avg: {trend_start:.1f} GB")
print(f"Last 5 months avg: {trend_end:.1f} GB")
print(f"Highest: {max_month} ({np.max(data_usage)} GB)")
print(f"Lowest: {min_month} ({np.min(data_usage)} GB)")

# Step 4: Reflection comment
print("\n[REFLECTION after analysis]")
print("My prediction was WRONG! I was surprised to find:")
print("1. Data usage is INCREASING over time, not stable")
print("2. June had the highest usage (82.3 GB) - not December!")
print("3. The trend shows +35% increase from first half to second half")
print("4. This suggests my streaming/usage habits changed significantly")
print("5. I need to upgrade my data plan before exceeding limits")



PROGRAM E — An Array of Your Choice

--- Example E1: Travel Time to College ---
Travel time from home to college (minutes):
  Monday: 35 minutes
  Tuesday: 42 minutes
  Wednesday: 38 minutes
  Thursday: 55 minutes
  Friday: 40 minutes
  Saturday: 33 minutes
  Sunday: 30 minutes

Average travel time: 39.0 minutes
Thursday travel time: 55 minutes
Thursday was 16.0 minutes above average
Conclusion: Yes, Thursday had unusual delay due to road construction near Maddilapalem.

--- Example E2: Virat Kohli IPL 2026 Performance ---
Virat Kohli's last 8 IPL innings:
  Innings 1: 78 runs
  Innings 2: 45 runs
  Innings 3: 0 runs
  Innings 4: 92 runs
  Innings 5: 56 runs
  Innings 6: 34 runs
  Innings 7: 88 runs
  Innings 8: 62 runs

Analysis:
  Innings above 50: 5 out of 8
  Innings below 20: 1 out of 8
  Standard deviation: 28.67 (lower = more consistent)
  Average in these 8 innings: 56.9
Source: ESPN Cricinfo match records, IPL 2026 season

--- Example E3: Mobile Data Usage Surprise ---
Monthl

## PROGRAM F — Identity Matrix in NumPy

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM F — Identity Matrix in NumPy")
print("=" * 60)

# -----------------------------------------------------------
# Example F1 — The No-Change Proof
# Context: Student marks matrix (3 subjects x 3 students)
# -----------------------------------------------------------
print("\n--- Example F1: No-Change Proof ---")

# 3x3 matrix: Rows = subjects, Columns = students
marks_matrix = np.array([
    [85, 78, 92],   # Data Analysis
    [76, 88, 81],   # DBMS
    [90, 85, 87]    # OS
])
students_f = ['Ravi', 'Priya', 'Amit']
subjects_f = ['Data Analysis', 'DBMS', 'OS']

print("Original Marks Matrix:")
print(marks_matrix)
print("Rows:", subjects_f)
print("Cols:", students_f)

# Create 3x3 identity matrix
I3 = np.eye(3)
print(f"\n3x3 Identity Matrix:")
print(I3)

# (i) Does A × I equal A? Verify this programmatically.
A_dot_I = np.dot(marks_matrix, I3)
is_equal_1 = np.allclose(marks_matrix, A_dot_I)

print(f"\n(i) A × I =")
print(A_dot_I)
print(f"    Does A × I equal A? {is_equal_1}")

# (ii) Does I × A also equal A? Show both directions.
I_dot_A = np.dot(I3, marks_matrix)
is_equal_2 = np.allclose(marks_matrix, I_dot_A)

print(f"\n(ii) I × A =")
print(I_dot_A)
print(f"     Does I × A equal A? {is_equal_2}")

# (iii) Comment on real-world use
print(f"\n(iii) [COMMENT]")
print("      This check is used in data pipelines to verify that")
print("      transformation matrices haven't accidentally altered the data.")
print("      If A × I ≠ A, it indicates a bug in the matrix operations.")


# -----------------------------------------------------------
# Example F2 — The Transformation Starting Point
# Context: Price matrix where identity = no discount, modification = apply discount
# -----------------------------------------------------------
print("\n--- Example F2: Price Transformation ---")

# Product prices matrix (3 categories x 3 products)
price_matrix = np.array([
    [500, 800, 1200],   # Electronics
    [200, 350, 500],    # Clothing
    [50, 100, 150]      # Groceries
])

print("Original Price Matrix (no discount = identity state):")
print(price_matrix)

# Identity represents "no discount applied yet"
I3_f2 = np.eye(3)
print(f"\nIdentity (baseline - no change):")
print(I3_f2)

# (i) Show result before applying modification
before_discount = np.dot(price_matrix, I3_f2)
print(f"\n(i) Before discount (A × I):")
print(before_discount)

# (ii) Apply meaningful change: 10% discount matrix
# Discount matrix: reduces each category by 10%
discount_matrix = np.array([
    [0.9, 0, 0],    # Electronics 10% off
    [0, 0.9, 0],    # Clothing 10% off
    [0, 0, 0.95]    # Groceries 5% off
])

after_discount = np.dot(price_matrix, discount_matrix)
print(f"\n(ii) After applying discount:")
print(after_discount)

# (iii) Interpret the change
savings = price_matrix - after_discount
total_savings = np.sum(savings)
print(f"\n(iii) [INTERPRETATION]")
print(f"       Total savings across all products: Rs {total_savings:.2f}")
print("       The identity matrix served as our baseline 'no discount' state.")
print("       The discount matrix transformed prices downward while preserving structure.")


# -----------------------------------------------------------
# Example F3 — The Pattern Discovery
# Context: Identity matrices of sizes 2,3,4,5 and their properties
# -----------------------------------------------------------
print("\n--- Example F3: Pattern Discovery ---")

sizes = [2, 3, 4, 5]
traces = []
determinants = []

print("Identity Matrix Properties:")
print(f"{'Size':>6} {'Trace':>10} {'Determinant':>14}")
print("-" * 35)

for n in sizes:
    I_n = np.eye(n)
    trace_n = np.trace(I_n)
    det_n = np.linalg.det(I_n)
    traces.append(trace_n)
    determinants.append(det_n)
    print(f"{n:>6} {trace_n:>10} {det_n:>14.6f}")

# (i) Pattern for trace
print(f"\n(i) [PATTERN - TRACE]")
print(f"    Traces: {traces}")
print(f"    Pattern: Trace of I_n = n (equals matrix size)")
print(f"    This is because trace sums diagonal elements, and identity has n ones on diagonal.")

# (ii) Pattern for determinant
print(f"\n(ii) [PATTERN - DETERMINANT]")
print(f"     Determinants: {[round(d, 6) for d in determinants]}")
print(f"     Pattern: det(I_n) = 1 for all n")
print(f"     This is because identity matrix represents no scaling/volume change.")

# (iii) General rule
print(f"\n(iii) [GENERAL RULE]")
print(f"      For any n×n identity matrix I_n:")
print(f"      • Trace(I_n) = n")
print(f"      • det(I_n) = 1")
print(f"      • These properties make identity matrix the multiplicative identity in linear algebra.")



PROGRAM F — Identity Matrix in NumPy

--- Example F1: No-Change Proof ---
Original Marks Matrix:
[[85 78 92]
 [76 88 81]
 [90 85 87]]
Rows: ['Data Analysis', 'DBMS', 'OS']
Cols: ['Ravi', 'Priya', 'Amit']

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

(i) A × I =
[[85. 78. 92.]
 [76. 88. 81.]
 [90. 85. 87.]]
    Does A × I equal A? True

(ii) I × A =
[[85. 78. 92.]
 [76. 88. 81.]
 [90. 85. 87.]]
     Does I × A equal A? True

(iii) [COMMENT]
      This check is used in data pipelines to verify that
      transformation matrices haven't accidentally altered the data.
      If A × I ≠ A, it indicates a bug in the matrix operations.

--- Example F2: Price Transformation ---
Original Price Matrix (no discount = identity state):
[[ 500  800 1200]
 [ 200  350  500]
 [  50  100  150]]

Identity (baseline - no change):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

(i) Before discount (A × I):
[[ 500.  800. 1200.]
 [ 200.  350.  500.]
 [  50.  100.  150.]]

(ii) After applying discount:
[[

## PROGRAM G — Evenly Spaced ndarray

In [ ]:
print("\n" + "=" * 60)
print("PROGRAM G — Evenly Spaced ndarray")
print("=" * 60)

# -----------------------------------------------------------
# Example G1 — The Scale Builder
# Context: Customer satisfaction score scale (0 to 10)
# Using linspace because we need exactly 11 points (0-10 inclusive)
# -----------------------------------------------------------
print("\n--- Example G1: Customer Satisfaction Scale ---")

# Using linspace: we need exactly 11 points with equal spacing
# Justification: We want specific count (11 points), not specific step size
satisfaction_scale = np.linspace(0, 10, 11)
print("Customer Satisfaction Scale (0-10, 11 points):")
print(satisfaction_scale)
print("[Used np.linspace because we need exactly 11 rating points]")

# Apply 5 real measurements from recent restaurant reviews
# Ratings from Google Reviews for local restaurants in Vizag
measurements = np.array([7.5, 8.2, 6.0, 9.1, 7.8])
print(f"\n5 Real Restaurant Ratings: {measurements}")

# Classify into zones
zones = []
for m in measurements:
    if m <= 4:
        zones.append('Poor')
    elif m <= 6:
        zones.append('Average')
    elif m <= 8:
        zones.append('Good')
    else:
        zones.append('Excellent')

print(f"\nClassifications:")
for m, z in zip(measurements, zones):
    print(f"  {m}: {z}")

# Count percentages
zone_counts = {'Poor': 0, 'Average': 0, 'Good': 0, 'Excellent': 0}
for z in zones:
    zone_counts[z] += 1

print(f"\nZone Distribution:")
for zone, count in zone_counts.items():
    pct = (count / len(measurements)) * 100
    print(f"  {zone}: {count} ({pct:.0f}%)")


# -----------------------------------------------------------
# Example G2 — The Schedule Generator
# Context: College bus timings from 6:00 AM to 10:00 PM every 30 minutes
# Using arange because we control the step (30 minutes)
# -----------------------------------------------------------
print("\n--- Example G2: College Bus Schedule ---")

# Convert time to minutes from midnight
# 6:00 AM = 360 minutes, 10:00 PM = 1320 minutes
# Step = 30 minutes
bus_times_minutes = np.arange(360, 1321, 30)  # 1321 to include 10:00 PM

print("College Bus Schedule (6:00 AM to 10:00 PM, every 30 min):")
print("[Used np.arange because we control the step size of 30 minutes]")

def minutes_to_time(m):
    hours = m // 60
    mins = m % 60
    ampm = "AM" if hours < 12 else "PM"
    hours = hours if hours <= 12 else hours - 12
    hours = 12 if hours == 0 else hours
    return f"{hours}:{mins:02d} {ampm}"

for i, t in enumerate(bus_times_minutes):
    print(f"  Slot {i+1}: {minutes_to_time(t)}")

# (i) How many total slots are generated?
total_slots = len(bus_times_minutes)
print(f"\n(i) Total bus slots: {total_slots}")

# (ii) Which slot number is closest to noon?
noon_minutes = 720
closest_to_noon_idx = np.argmin(np.abs(bus_times_minutes - noon_minutes))
closest_slot = closest_to_noon_idx + 1
print(f"\n(ii) Slot closest to noon (12:00 PM): Slot {closest_slot} ({minutes_to_time(bus_times_minutes[closest_to_noon_idx])})")

# (iii) If 3 slots are cancelled, how many remain and what is the new utilisation rate?
cancelled = 3
remaining = total_slots - cancelled
utilisation = (remaining / total_slots) * 100
print(f"\n(iii) After cancelling {cancelled} slots:")
print(f"       Remaining slots: {remaining}")
print(f"       Utilisation rate: {utilisation:.1f}%")


# -----------------------------------------------------------
# Example G3 — The Discovery
# Context: Compound interest comparison at 5%, 8%, and 12% over 20 years
# Find: At which year does 12% investment double the 5% investment?
# Using arange because we control step (1 year)
# -----------------------------------------------------------
print("\n--- Example G3: Compound Interest Discovery ---")

principal = 100000  # Rs 1 lakh
years = np.arange(0, 21, 1)  # 0 to 20 years, step 1

# [Used np.arange because we need yearly steps of exactly 1 year]
print("Compound Interest Growth (Principal: Rs 1,00,000)")
print("[Used np.arange because we control the step size of 1 year]")

rate_5 = principal * (1.05 ** years)
rate_8 = principal * (1.08 ** years)
rate_12 = principal * (1.12 ** years)

print(f"\n{'Year':>6} {'5%':>12} {'8%':>12} {'12%':>12} {'12%/5%':>10}")
print("-" * 58)

for i, y in enumerate(years):
    ratio = rate_12[i] / rate_5[i]
    print(f"{y:>6} {rate_5[i]:>12.0f} {rate_8[i]:>12.0f} {rate_12[i]:>12.0f} {ratio:>10.2f}x")

# Find threshold: when does 12% value become > 2x the 5% value?
ratio_array = rate_12 / rate_5
threshold_mask = ratio_array > 2
threshold_years = years[threshold_mask]

if len(threshold_years) > 0:
    first_threshold_year = threshold_years[0]
    print(f"\n(i) Threshold found: Year {first_threshold_year}")
    print(f"    At year {first_threshold_year}: 12% value = Rs {rate_12[first_threshold_year]:.0f}")
    print(f"    5% value = Rs {rate_5[first_threshold_year]:.0f}")
    print(f"    Ratio = {ratio_array[first_threshold_year]:.2f}x")
else:
    print(f"\n(i) 12% investment does not double the 5% investment within 20 years")

# (ii) One-line conclusion
print(f"\n(ii) [CONCLUSION]")
print(f"      # At {first_threshold_year} years, the 12% investment becomes more than double the 5% investment,")
print(f"      # demonstrating the power of compound interest rate differences over time.")

# (iii) Function justification
print(f"\n(iii) [FUNCTION JUSTIFICATION]")
print(f"      Used np.arange(0, 21, 1) because:")
print(f"      - We need yearly intervals (step = 1)")
print(f"      - np.linspace would give fractional years which don't make sense for annual compounding")
print(f"      - arange naturally generates integer year indices")

print("\n" + "=" * 60)
print("ASSIGNMENT COMPLETE — All Programs Executed Successfully")
print("=" * 60)



PROGRAM G — Evenly Spaced ndarray

--- Example G1: Customer Satisfaction Scale ---
Customer Satisfaction Scale (0-10, 11 points):
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[Used np.linspace because we need exactly 11 rating points]

5 Real Restaurant Ratings: [7.5 8.2 6.  9.1 7.8]

Classifications:
  7.5: Good
  8.2: Excellent
  6.0: Average
  9.1: Excellent
  7.8: Good

Zone Distribution:
  Poor: 0 (0%)
  Average: 1 (20%)
  Good: 2 (40%)
  Excellent: 2 (40%)

--- Example G2: College Bus Schedule ---
College Bus Schedule (6:00 AM to 10:00 PM, every 30 min):
[Used np.arange because we control the step size of 30 minutes]
  Slot 1: 6:00 AM
  Slot 2: 6:30 AM
  Slot 3: 7:00 AM
  Slot 4: 7:30 AM
  Slot 5: 8:00 AM
  Slot 6: 8:30 AM
  Slot 7: 9:00 AM
  Slot 8: 9:30 AM
  Slot 9: 10:00 AM
  Slot 10: 10:30 AM
  Slot 11: 11:00 AM
  Slot 12: 11:30 AM
  Slot 13: 12:00 PM
  Slot 14: 12:30 PM
  Slot 15: 1:00 PM
  Slot 16: 1:30 PM
  Slot 17: 2:00 PM
  Slot 18: 2:30 PM
  Slot 19: 3:00 PM
  Slot 20