<a href="https://colab.research.google.com/github/malcommathela/Data-Analysis/blob/main/Data_Analysis_Essentials_Weeks_1_7_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis Essentials: Weeks 1–7 Quiz
**Name:** Malcom Mathela (25B11CSA68) — Final score: 14/15


## Q1 — NumPy eye + linspace
What is printed?

A) 5.0  B) **6.0** ✅  C) 3.5  D) 1.0

In [1]:
import numpy as np

a = np.eye(3, k=1)          # 3x3 identity with 1s on the superdiagonal
b = np.linspace(0, 10, 5)   # [0. 2.5 5. 7.5 10.]
print(a[0, 1] + b[2])       # 1 + 5.0 = 6.0

6.0


## Q2 — flatten() is a copy
What is printed?

A) 99  B) **0** ✅  C) 12  D) IndexError

`flatten()` always returns a **copy**, so modifying `flat` does not affect `arr`.

In [2]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
flat = arr.flatten()
flat[0] = 99
print(arr[0, 0])   # 0 — flatten() returned a copy

0


## Q3 — squeeze + expand_dims
What is printed?

A) **(4, 1, 3)** ✅  B) (1, 4, 3)  C) (4, 3, 1)  D) (1, 1, 4, 3)

In [3]:
import numpy as np

x = np.ones((1, 4, 1, 3))
y = np.squeeze(x)              # (4, 3)
z = np.expand_dims(y, axis=1)  # (4, 1, 3)
print(z.shape)

(4, 1, 3)


## Q4 — Reversed row slicing
What is printed?

A) 20  B) 60  C) **100** ✅  D) 110

In [4]:
import numpy as np

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])
subset = arr[::-1, 1:3]   # rows reversed, then cols 1:3
print(subset)             # [[100 110], [60 70], [20 30]]
print(subset[0, 0])       # 100

[[100 110]
 [ 60  70]
 [ 20  30]]
100


## Q5 — Boolean sum after concat
What is printed?

A) 1  B) **2** ✅  C) 3  D) 4

In [5]:
import pandas as pd

df1 = pd.DataFrame({'A': [10, 20], 'B': [30, 40]})
df2 = pd.DataFrame({'A': [5, 25], 'B': [15, 35]})

combined = pd.concat([df1, df2], ignore_index=True)
combined['Flag'] = combined['A'] >= 20   # [False, True, False, True]
print(combined['Flag'].sum())            # 2

2


## Q6 — fillna + groupby mean
What is printed?

A) 70  B) **75** ✅  C) 80  D) 85

IT scores: 80 and 70 → mean = 75.

In [6]:
import pandas as pd
import numpy as np

data = {
    'Dept': ['IT', 'HR', 'IT', np.nan, 'HR'],
    'Score': [80, 90, 70, 60, 85]
}
df = pd.DataFrame(data)
df['Dept'] = df['Dept'].fillna('Unknown')
res = df.groupby('Dept')['Score'].mean()['IT']  # (80 + 70) / 2 = 75
print(int(res))

75


## Q7 — stack vs vstack
What is printed?

A) **True (2, 3)** ✅  B) False (3, 2)  C) True (3, 2)  D) False (2, 3)

In [7]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.stack((a, b), axis=0)  # shape (2, 3)
d = np.vstack((a, b))         # shape (2, 3) — identical result
print(np.array_equal(c, d), c.shape)

True (2, 3)


## Q8 — Broadcasting shape pairs (MSQ)
**Correct answers: A, B, C** ✅✅✅ — D fails

NumPy aligns trailing dimensions **right-to-left**; dims are compatible if equal or one of them is 1.

- A) (8,1,6,1) & (7,1,5) → (8,7,6,5) ✅
- B) (5,4) & (4,) → (5,4) ✅
- C) (3,1,5) & (3,4,1) → (3,4,5) ✅


In [9]:
import numpy as np

pairs = [
    ((8, 1, 6, 1), (7, 1, 5)),   # A
    ((5, 4), (4,)),              # B
    ((3, 1, 5), (3, 4, 1)),      # C
    ((3, 3), (3, 2)),            # D
]
for i, (sa, sb) in enumerate(pairs):
    try:
        out = np.broadcast_shapes(sa, sb)
        print(f"{chr(65+i)}) {sa} & {sb} -> OK, result shape {out}")
    except ValueError as e:
        print(f"{chr(65+i)}) {sa} & {sb} -> ERROR: {e}")

A) (8, 1, 6, 1) & (7, 1, 5) -> OK, result shape (8, 7, 6, 5)
B) (5, 4) & (4,) -> OK, result shape (5, 4)
C) (3, 1, 5) & (3, 4, 1) -> OK, result shape (3, 4, 5)
D) (3, 3) & (3, 2) -> ERROR: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3, 3) and arg 1 with shape (3, 2).


## Q9 — Views vs copies (MSQ)
Which operations return a VIEW (modifying the result affects the original)?

A) **arr[1:4, ::2]** ✅  B) **arr.T** ✅  C)

In [10]:
import numpy as np

arr = np.arange(24).reshape(6, 4)

view1 = arr[1:4, ::2]
print("A slicing shares memory:", np.shares_memory(view1, arr))    # True

view2 = arr.T
print("B transpose shares memory:", np.shares_memory(view2, arr))  # True

print("C flatten shares memory:", np.shares_memory(arr.flatten(), arr))  # False
print("D copy shares memory:  ", np.shares_memory(arr.copy(), arr))      # False

A slicing shares memory: True
B transpose shares memory: True
C flatten shares memory: False
D copy shares memory:   False


## Q10 — Total sales per branch, highest to lowest
Correct option: **C** ✅


In [11]:
import pandas as pd

df = pd.DataFrame({
    'Branch': ['North', 'South', 'North', 'East', 'South', 'East', 'North'],
    'Sales':  [100, 200, 150, 300, 250, 50, 400]
})

# Correct answer (C):
result = df.groupby('Branch', as_index=False)['Sales'].sum().sort_values(by='Sales', ascending=False)
print(result)

# Option A also yields the correct ordering, as a Series:
# print(df.groupby('Branch')['Sales'].sum().sort_values(ascending=False))

  Branch  Sales
1  North    650
2  South    450
0   East    350


## Q11 — TRUE statements about NumPy (MSQ)
a) **TRUE** ✅ — np.zeros defaults to float64 (0.0)


In [12]:
import numpy as np

# a) True
print(np.zeros((3, 2)).dtype)       # float64

# b) False
print(np.arange(1, 10, 2))          # [1 3 5 7 9] — 10 excluded

# c) True
print(np.array([10, 20, 30])[-1])   # 30

# d) False
print(np.random.rand(2, 3))         # uniform [0,1); standard normal = np.random.randn

float64
[1 3 5 7 9]
30
[[0.69284131 0.60895377 0.41884587]
 [0.50067729 0.2686588  0.89391039]]


## Q12 — NAT: ndim × size
**Answer: 72** — ndim = 3, size = 2×3×4 = 24 → 3 × 24 = 72

In [13]:
import numpy as np

arr = np.zeros((2, 3, 4), dtype=int)
total = arr.ndim * arr.size   # 3 * 24
print(total)                  # 72

72


## Q13 — NAT: 3-D slice sum
**Answer: 34** — arr[1, 0:2, -1] picks 15 and 19 → 15 + 19 = 34

In [14]:
import numpy as np

arr = np.arange(24).reshape(2, 3, 4)
print(arr[1])
val = arr[1, 0:2, -1].sum()   # rows 0-1, last column -> 15 + 19
print(val)                    # 34

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
34


## Q14 — NAT: concatenate sum
**Answer: 30** — six 1s (sum 6) + six 4s (sum 24) = 30; concatenating along axis 1 doesn't change the total.

In [15]:
import numpy as np

a = np.ones((2, 3))
b = np.full((2, 3), 4)
c = np.concatenate((a, b), axis=1)
print(c.shape, int(c.sum()))  # (2, 6) 30

(2, 6) 30


## Q15 — NAT: filtered row count
**Answer: 2** — non-Goa adjusted sales: Pune 220, Delhi 440, Pune 550 → only 440 and 550 are > 250.

In [16]:
import pandas as pd

df = pd.DataFrame({
    'City': ['Goa', 'Pune', 'Goa', 'Delhi', 'Pune'],
    'Sales': [100, 200, 300, 400, 500]
})

df['Adjusted'] = df['Sales'] * 1.10
filtered = df[(df['City'] != 'Goa') & (df['Adjusted'] > 250)]
print(filtered)
print(len(filtered))   # 2

    City  Sales  Adjusted
3  Delhi    400     440.0
4   Pune    500     550.0
2
