# Week-5: Stacking and Concatenating NumPy Arrays
Combining arrays vertically, horizontally, in depth, along arbitrary axes, plus broadcasting.

## a. Stacking ndarrays
`vstack` piles rows, `hstack` joins columns, `dstack` layers 2D grids into depth.

In [1]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([7, 8, 9])
print(f'Vertical stack:\n{np.vstack((x, y))}')
print(f'Horizontal stack: {np.hstack((x, y))}')

p = np.array([[1, 2], [3, 4]])
q = np.array([[9, 8], [7, 6]])
deep = np.dstack((p, q))
print(f'Depth stack:\n{deep}  (shape {deep.shape})')

Vertical stack:
[[1 2 3]
 [7 8 9]]
Horizontal stack: [1 2 3 7 8 9]
Depth stack:
[[[1 9]
  [2 8]]

 [[3 7]
  [4 6]]]  (shape (2, 2, 2))


## b. Concatenating ndarrays
`np.concatenate` joins along an axis that already exists (axis=0: rows, axis=1: columns).

In [2]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[9, 8], [7, 6]])
print(f'Along axis=0 (rows):\n{np.concatenate((m1, m2), axis=0)}')
print(f'Along axis=1 (columns):\n{np.concatenate((m1, m2), axis=1)}')

Along axis=0 (rows):
[[1 2]
 [3 4]
 [9 8]
 [7 6]]
Along axis=1 (columns):
[[1 2 9 8]
 [3 4 7 6]]


## c. Broadcasting in NumPy Arrays
Shapes are compatible when dimensions are equal or one of them is 1; size-1 axes stretch virtually.

In [3]:
import numpy as np

arr = np.array([2, 4, 6, 8])
print(f'Array:       {arr}')
print(f'Array + 10:  {arr + 10}')
print(f'Array * 3:   {arr * 3}')

col = np.array([[1], [2], [3]])
row = np.array([10, 20, 30])
print(f'(3,1) + (3,) broadcasts to (3,3):\n{col + row}')

Array:       [2 4 6 8]
Array + 10:  [12 14 16 18]
Array * 3:   [ 6 12 18 24]
(3,1) + (3,) broadcasts to (3,3):
[[11 21 31]
 [12 22 32]
 [13 23 33]]
