<a href="https://colab.research.google.com/github/malcommathela/Data-Analysis/blob/main/Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Axes**

In [ ]:
import numpy as np

## 1d Array
arr_1d = np.array([1,2,3,4])
print("1D Array:\n", arr_1d)
print("Sum (Axis 0): ", np.sum(arr_1d, axis = 0))

## 2D
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D Array:\n", arr_2d)
print("Sum (Axis 0): ", np.sum(arr_2d, axis = 0))
print("Sum (Axis 1): ", np.sum(arr_2d, axis = 1))

#3D
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("\n3D Array:\n", arr_3d)
print("Sum along layers (Axis 0): \n", np.sum(arr_3d, axis = 0))
print("Sum along Rows (Axis 0): \n", np.sum(arr_3d, axis = 1))
print("Sum along Columns (Axis 0): \n", np.sum(arr_3d, axis = 2))
print("Overall Sum: ", np.sum(arr_3d))






1D Array:
 [1 2 3 4]
Sum (Axis 0):  10
2D Array:
 [[1 2 3]
 [4 5 6]]
Sum (Axis 0):  [5 7 9]
Sum (Axis 1):  [ 6 15]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Sum along layers (Axis 0): 
 [[ 6  8]
 [10 12]]
Sum along Rows (Axis 0): 
 [[ 4  6]
 [12 14]]
Sum along Columns (Axis 0): 
 [[ 3  7]
 [11 15]]
Overall Sum:  36


# **Expanding a NumPy array**

Syntax

In [ ]:
np.expand_dims(array, axis)

Example 1: Convert 1D array to Row Vector

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

expanded = np.expand_dims(arr, axis=0)

print(expanded)
print(expanded.shape)

[[1 2 3 4]]
(1, 4)


Example 2: Convert 1D array to Column Vector

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

expanded = np.expand_dims(arr, axis=1)

print(expanded)
print(expanded.shape)

Example 3: Expanding a 2D Array to 3D

In [ ]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

expanded = np.expand_dims(arr, axis=0)

print(expanded)
print(expanded.shape)

# Squeezing a NumPy **array**

Syntax

In [ ]:
np.squeeze(array, axis=None)

Example 1: Squeezing a 2D Array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3]])

print("Original Shape:", arr.shape)

squeezed = np.squeeze(arr)

print("Squeezed Array:")
print(squeezed)
print("New Shape:", squeezed.shape)

Example 2: Squeezing a 3D Array

In [ ]:
import numpy as np

arr = np.array([[[1, 2],
                 [3, 4]]])

print("Original Shape:", arr.shape)

squeezed = np.squeeze(arr)

print(squeezed)
print("New Shape:", squeezed.shape)

Original Shape: (1, 2, 2)
[[1 2]
 [3 4]]
New Shape: (2, 2)


Example 3: Using axis

In [ ]:
import numpy as np

arr = np.array([[[10, 20, 30]]])

print(arr.shape)

result = np.squeeze(arr, axis=0)

print(result)
print(result.shape)

# Sorting in NumPy **Arrays**

Syntax

In [ ]:
np.sort(array, axis=-1)

Sorting a 1D Array

In [ ]:
import numpy as np

arr = np.array([5, 2, 8, 1, 9])

sorted_arr = np.sort(arr)

print("Original Array:", arr)
print("Sorted Array:", sorted_arr)

Sorting a 2D Array (Rows)

In [ ]:
import numpy as np

arr = np.array([[3, 1, 2],
                [9, 5, 7]])

print(np.sort(arr, axis=1))

Sorting a 2D Array (Columns)

In [ ]:
import numpy as np

arr = np.array([[3, 1, 2],
                [9, 5, 7]])

print(np.sort(arr, axis=0))

Sorting a 3D Array

In [ ]:
import numpy as np

arr = np.array([
    [[3, 1], [4, 2]],
    [[8, 6], [7, 5]]
])

print(np.sort(arr, axis=2))