<a href="https://colab.research.google.com/github/malcommathela/Data-Analysis/blob/main/Week_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Slicing 1-D NumPy **Arrays**

In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])

Example 1: Elements from index 1 to **4**

In [ ]:
print(arr[1:5])
# Output: [20 30 40 50]

[20 30 40 50]


Example 2: First four elements

In [ ]:
print(arr[:4])
# Output: [10 20 30 40]

[10 20 30 40]


Example 3: Every second element

In [ ]:
print(arr[::2])
# Output: [10 30 50 70]

[10 30 50 70]


# Slicing 2-D NumPy **Arrays**

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

Example 1: First two rows

In [ ]:
print(arr[:2])
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


Example 2: First two rows and first two columns

In [ ]:
print(arr[:2, :2])
# Output:
# [[1 2]
#  [4 5]]

[[1 2]
 [4 5]]


Example 3: Second column

In [ ]:
print(arr[:, 1])
# Output:
# [2 5 8]

[2 5 8]


# Slicing 3-D NumPy **Arrays**

In [ ]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

Example 1: First 2-D array

In [ ]:
print(arr[0])
# Output:
# [[1 2]
#  [3 4]]

[[1 2]
 [3 4]]


Example 2: First row from both 2-D arrays

In [ ]:
print(arr[:, 0, :])
# Output:
# [[1 2]
#  [5 6]]

[[1 2]
 [5 6]]


Example 3: Second column from every row in every 2-D array

In [ ]:
print(arr[:, :, 1])
# Output:
# [[2 4]
#  [6 8]]

[[2 4]
 [6 8]]


# Negative Slicing of NumPy **Arrays**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70])

Example 1: Last three elements of a 1-D array

In [ ]:
print(arr[-3:])
# Output:
# [50 60 70]

[50 60 70]


Example 2: Reverse a 1-D array

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[::-1])
# Output:
# [50 40 30 20 10]

[50 40 30 20 10]


Example 3: Last two rows of a 2-D array

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print(arr[-2:])
# Output:
# [[4 5 6]
#  [7 8 9]]

[[4 5 6]
 [7 8 9]]
