# Week-4: Indexing and Slicing of NumPy Arrays
Multi-axis slice syntax `[start:stop:step]` across 1D, 2D, and 3D arrays.

## a. Slicing 1-D NumPy Arrays
Slice ranges exclude the stop index; negative indices count from the end.

In [1]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(f'Array: {arr}')
print(f'arr[2:6] -> {arr[2:6]}')
print(f'arr[2]   -> {arr[2]}')
print(f'arr[::2] -> {arr[::2]}  (every 2nd element)')
print(f'arr[-1]  -> {arr[-1]}  (last element)')

Array: [ 5 10 15 20 25 30 35]
arr[2:6] -> [15 20 25 30]
arr[2]   -> 15
arr[::2] -> [ 5 15 25 35]  (every 2nd element)
arr[-1]  -> 35  (last element)


## b. Slicing 2-D NumPy Arrays
Use comma syntax `[rows, cols]`; a lone `:` selects the whole axis.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(f'Matrix:\n{arr}')
print(f'Rows 0-1, Cols 1-2 (arr[0:2, 1:3]):\n{arr[0:2, 1:3]}')
print(f'Last row (arr[-1]):       {arr[-1]}')
print(f'First column (arr[:, 0]): {arr[:, 0]}')

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Rows 0-1, Cols 1-2 (arr[0:2, 1:3]):
[[2 3]
 [6 7]]
Last row (arr[-1]):       [ 9 10 11 12]
First column (arr[:, 0]): [1 5 9]


## c. Slicing 3-D NumPy Arrays
Dimensions read as [block, row, col]; `...` fills in the remaining colons.

In [3]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
print(f'3D array shape: {arr.shape}')
print(f'First block (arr[0]):\n{arr[0]}')
print(f'Second block (arr[1, :, :]):\n{arr[1, :, :]}')
print(f'First rows of each block (arr[:, 0, :]): {arr[:, 0, :]}')
print(f'Column 1 across blocks (arr[..., 1]):    {arr[..., 1]}')

3D array shape: (2, 2, 3)
First block (arr[0]):
[[1 2 3]
 [4 5 6]]
Second block (arr[1, :, :]):
[[ 7  8  9]
 [10 11 12]]
First rows of each block (arr[:, 0, :]): [[1 2 3]
 [7 8 9]]
Column 1 across blocks (arr[..., 1]):    [[ 2  5]
 [ 8 11]]


## d. Negative Slicing of NumPy Arrays
A negative step walks the buffer backwards, reversing the array without copying.

In [4]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25, 30, 35])
print(f'Array: {arr}')
print(f'arr[-4:-1] -> {arr[-4:-1]}')
print(f'arr[-3:]   -> {arr[-3:]}')
print(f'arr[::-1]  -> {arr[::-1]}  (fully reversed)')

Array: [ 5 10 15 20 25 30 35]
arr[-4:-1] -> [20 25 30]
arr[-3:]   -> [25 30 35]
arr[::-1]  -> [35 30 25 20 15 10  5]  (fully reversed)
